### ISSUE TITLE
But, see here: this monkey's life was suddenly elsewhere, in his time. This secret was called Eccles.

### ISSUE THREAD

**Issue by roadtojoy** [rossfuhrman/_why_the_lucky_markov#104]
Toot: But, see here: this monkey's life was suddenly elsewhere, in his time. This secret was called Eccles. 
 One comment = 1 upvote. Sometime after this gets 2 upvotes, it will be posted to the main account at https://mastodon.xyz/@_why_toots

**Comment by chrismo** [comment]
+1

**Comment by chrismo** [comment]
+1

**Comment by rossfuhrman** [comment]
+1
