### ISSUE TITLE
You gotta admit. Michel's wife ventured into the ground with scrambled words, but he was tormented by her ghost, which glistened gold and scorched lace.

### ISSUE THREAD

**Issue by roadtojoy** [rossfuhrman/_why_the_lucky_markov#88]
Toot: You gotta admit. Michel's wife ventured into the ground with scrambled words, but he was tormented by her ghost, which glistened gold and scorched lace. 
 One comment = 1 upvote. Sometime after this gets 2 upvotes, it will be posted to the main account at https://mastodon.xyz/@_why_toots

**Comment by chrismo** [comment]
+1

**Comment by chrismo** [comment]
+1
